#!/bin/bash

# LIBS module load cuda/11_local

################################################################################################
echo "==== Start of GPU information ===="

CUDA_DEVICE=$(echo "$CUDA_VISIBLE_DEVICES," | cut -d',' -f $((SLURM_LOCALID + 1)) );
T_REGEX='^[0-9]$';
if ! [[ "$CUDA_DEVICE" =~ $T_REGEX ]]; then
        echo "error no reserved gpu provided"
        exit 1;
fi

# Print debug information

echo -e "SLURM job:\t$SLURM_JOBID"
#echo -e "SLURM process:\t$SLURM_PROCID"
#echo -e "SLURM GPU ID:\t$SLURM_LOCALID"
#echo -e "CUDA_DEVICE ID:\t$CUDA_DEVICE"
echo -e "CUDA_VISIBLE_DEVICES:\t$CUDA_VISIBLE_DEVICES"
echo "Device list:"
echo "$(nvidia-smi --query-gpu=name,gpu_uuid --format=csv -i $CUDA_VISIBLE_DEVICES | tail -n +2)"
echo "==== End of GPU information ===="
echo ""
#################################################################################################

# we need to export ALL otherwise this won't work!
# if ! command -v scaden &> /dev/null
# then
#     source /prj/MAGE/analysis/deconvolution/scaden/.scaden/bin/activate
# fi

if [[ $TRAIN -eq 1 ]]
then
    scaden train --model_dir $MODEL_DIR --batch_size $BATCH_SIZE --learning_rate $LEARNING_RATE --steps \
    $STEPS --seed $SEED $TRAINING_DATA
else
    scaden predict --model_dir $MODEL_DIR --outname $OUTNAME --seed $SEED $BULK
fi
